name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        name: Checkout
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        name: Install Node.js
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
        name: Install dependencies
      - run: npm run build --if-present
        name: Build
      - run: npm run lint --if-present
        name: Lint
      - run: npm run test:cov
        name: Test
      - uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
        name: Upload coverage to Codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
